version: 2

sources:
  - name: raw
    schema: raw_data_circle     # schema in dbt = dataset in bigquery
    tables:
      - name: sales
        identifier: raw_cc_sales   # identifier in dbt = table in bigquery
        columns:
          - name: date_date
            tests: 
              - not_null
          - name: product_id
            tests:
              - not_null
        tests:
          - unique:
              column_name: "date_date || product_id"
          
              
      - name: stock
        identifier: raw_cc_stock
        columns:
          - name: model
            tests:
              - not_null
              