version: 2

sources:
  - name: raw
    schema: raw_data_circle     # schema in dbt = dataset in bigquery
    tables:
      - name: sales
        identifier: raw_cc_sales   # identifier in dbt = table in bigquery
        columns:
          - name: date_date
            tests: 
              - not_null
          - name: product_id
            tests:
              - not_null
        tests:
          - unique:
              column_name: "date_date || product_id"
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - date_date
                - product_id
              
      - name: stock
        identifier: raw_cc_stock
        columns:
          - name: model
            tests:
              - not_null

      - name: parcel
        identifier: raw_cc_parcel
        columns:
          - name: parcel_id
            tests:
              - not_null
              - unique
          - name: date_purchase
            tests:
              - not_null
              

      - name: parcel_product
        identifier: raw_cc_parcel_product
        columns:
          - name: parcel_id
            tests:
              - not_null
          - name: model_mame
            tests:
              - not_null
        tests:
          - unique:
              column_name: "parcel_id || model_mame"
          - not_null:
              column_name: "parcel_id || model_mame"



